
export const EVENT_STATUSES = [
  { value: "draft",     label: "Draft",     color: "var(--muted)" },
  { value: "active",    label: "Active",    color: "var(--accent)" },
  { value: "live",      label: "Live",      color: "#22c55e" },
  { value: "completed", label: "Completed", color: "var(--success)" },
  { value: "archived",  label: "Archived",  color: "#555" },
];
export const statusMeta = (val) => EVENT_STATUSES.find(s => s.value === val) || EVENT_STATUSES[0];

export const APPARATUS_GROUPS = [
  { label: "WAG (Women's)", items: ["Floor", "Bars", "Beam", "Vault", "Range"] },
  { label: "MAG (Men's)", items: ["Floor", "Pommel Horse", "Rings", "Vault", "Parallel Bars", "Horizontal Bar"] },
];
export const APPARATUS_OPTIONS = APPARATUS_GROUPS.flatMap(g => g.items.map(a => `${a} (${g.label.split(" ")[0]})`));

// Migrate old bare apparatus names (e.g. "Beam") → new format ("Beam (WAG)")
export const APPARATUS_MIGRATE = {};
APPARATUS_GROUPS.forEach(g => {
  const tag = g.label.split(" ")[0];
  g.items.forEach(a => { if (!APPARATUS_MIGRATE[a]) APPARATUS_MIGRATE[a] = `${a} (${tag})`; });
});

export const UK_LEVELS = [
  { group: "Classic Challenge", options: ["Tin", "Zinc", "Copper", "Bronze", "Silver", "Gold"] },
  { group: "NDP Grades (Club/County)", options: ["Prep Grade 1", "Prep Grade 2", "Prep Grade 3", "Dev Grade 1", "Dev Grade 2", "Dev Grade 3", "Performance Grade 1", "Performance Grade 2", "Performance Grade 3"] },
  { group: "NDP Grades (Regional/National)", options: ["Grade 14", "Grade 13", "Grade 12", "Grade 11", "Grade 10", "Grade 9", "Grade 8", "Grade 7", "Grade 6", "Grade 5"] },
  { group: "Elite / NDP Compulsory", options: ["Level 4", "Level 3", "Level 2", "Espoir", "Junior", "Senior"] },
  { group: "FIG / International", options: ["FIG Dev 1", "FIG Dev 2", "FIG Dev 3", "FIG Junior", "FIG Senior"] },
];
export const UK_LEVELS_FLAT = UK_LEVELS.flatMap(g => g.options);

// ============================================================
// UK GYMNASTICS CLUBS — scraped from BG results PDFs 2024
// Sources: British Championships, Adult Championships, English
// Rhythmic Championships, Acrobatic Championships, Disability
// Championships. Covers WAG, MAG, Rhythmic, Acrobatic, Tumbling.
// Add more clubs at the bottom of this array as needed.
// ============================================================
export const UK_CLUBS = [
  { name: "1066 Gymnastics", locations: ["Bexhill-on-sea"] },
  { name: "776 Gymnastics", locations: ["Mansfield"] },
  { name: "776 Gymnastics Commercial Road", locations: ["Sunderland"] },
  { name: "776 Gymnastics Front Street", locations: ["Stanley"] },
  { name: "776 Gymnastics Grindon Lane", locations: ["Sunderland"] },
  { name: "776 Gymnastics Newark", locations: ["Newark"] },
  { name: "776 Gymnastics Penshaw", locations: ["Houghton Le Spring"] },
  { name: "776 Gymnastics Shakespeare Street", locations: ["Sunderland"] },
  { name: "776 Gymnastics Southgate", locations: ["Newcastle Upon Tyne"] },
  { name: "776 Gymnastics St. Peters Road", locations: ["Wallsend"] },
  { name: "AB FAB Gymnastics", locations: ["Retford"] },
  { name: "Abbey Gym Club", locations: ["Great Middenden"] },
  { name: "Abbey Gymnastics C.I.C.", locations: ["Belfast"] },
  { name: "Abbey High Fliers", locations: ["Peterborough"] },
  { name: "Aberdeen Acro GC", locations: ["Aberdeen"] },
  { name: "Aberdeen GC", locations: ["Aberdeen"] },
  { name: "Aberdeen University Trampoline Club", locations: ["Aberdeen"] },
  { name: "Aberdeenshire Aspire Trampoline Academy", locations: ["Inverurie"] },
  { name: "Abingdon Gymnastics Club", locations: ["Wallingford"] },
  { name: "Aboyne GC &", locations: ["Aboyne", "Banchory"] },
  { name: "AC Elite Gymnastics Club", locations: ["Dorking"] },
  { name: "Academy Gymnastics", locations: ["Evesham", "Rugby"] },
  { name: "Accelerate Trampoline", locations: ["Taunton", "Wellington", "Willand", "Yeovil"] },
  { name: "Acceleration Trampoline Club", locations: ["Reading"] },
  { name: "ACE Gymnastics Perth", locations: ["Perth"] },
  { name: "Acklam Gym Club", locations: ["Middlesbrough"] },
  { name: "Acrobay", locations: ["Dunfermline"] },
  { name: "Acromax Group (The)", locations: ["St Leonards-On-Sea"] },
  { name: "AcroNova Gymnastics", locations: ["Birkenhead"] },
  { name: "Activ8 Trampoline Club", locations: ["Sutton Coldfield", "Tamworth"] },
  { name: "Active", locations: ["Walsall"] },
  { name: "Active GC", locations: ["ELGIN"] },
  { name: "Active Gymnastics Club", locations: ["London"] },
  { name: "Active Gymnastics Club Dorset", locations: ["Poole"] },
  { name: "Adams Gymnastics", locations: ["Leicester"] },
  { name: "Advance Gymnastics Club", locations: ["Croydon"] },
  { name: "Aerial Gymnastics Academy", locations: ["Liverpool"] },
  { name: "Aerial Tumbling", locations: ["Epsom"] },
  { name: "Aerial Tumbling Club", locations: ["Leatherhead"] },
  { name: "Aerodyne", locations: ["South Shields"] },
  { name: "Aeronauts Trampoline", locations: ["Hartlepool"] },
  { name: "Air Acro Gymnastics", locations: ["HAYWARDS HEATH"] },
  { name: "Air Dynamix", locations: ["Halesowen"] },
  { name: "Air Extreme Trampoline", locations: ["Barnstaple"] },
  { name: "Airborne Gymnastics", locations: ["Stoke health"] },
  { name: "AIRBORNE GYMNASTICS", locations: ["Maidenhead"] },
  { name: "Aire Trampoline", locations: ["Canterbury", "Sandwich"] },
  { name: "Aire Trampoline Club", locations: ["Dover"] },
  { name: "Aireborough Gymnastics", locations: ["Leeds"] },
  { name: "Airies Gymnastics Club", locations: ["Langley"] },
  { name: "Alba Trampoline Club", locations: ["Glasgow", "Kilmarnock"] },
  { name: "Alchemy Trampoline & DMT", locations: ["Nailsea"] },
  { name: "alienZoo", locations: ["LONDON", "London", "Southampton"] },
  { name: "All Star Elite Trampoline & DMT Team", locations: ["East Kilbride"] },
  { name: "Allander Gymnastics Club", locations: ["Glasgow"] },
  { name: "Allegro Gymnastics Academy", locations: ["Scunthorpe"] },
  { name: "Allegro School of Gymnastics", locations: ["Bromley", "Orpington"] },
  { name: "Alloa Amateur GC", locations: ["Alloa"] },
  { name: "Allstarz", locations: ["Croydon"] },
  { name: "Alpha Trampoline Club", locations: ["Alton"] },
  { name: "Altair Trampoline", locations: ["Birmingham"] },
  { name: "Altitude Trampoline", locations: ["Halstead"] },
  { name: "Alton Gymnastics Club", locations: ["Alton"] },
  { name: "Alton Trampoline Club", locations: ["Alton"] },
  { name: "Alvah Gymteam", locations: ["Aberdeen", "Macduff"] },
  { name: "Alvechurch Gymnastics Club", locations: ["Alvechurch"] },
  { name: "Ambitions", locations: ["Crosshills"] },
  { name: "Andover Gymnastics", locations: ["Andover"] },
  { name: "Anima Gymnastics Club", locations: ["London"] },
  { name: "Anna's Gymnastics", locations: ["London"] },
  { name: "Anna's Gymnastics Academy", locations: ["London"] },
  { name: "Antrim Phoenix Gymnastics Club", locations: ["ANTRIM", "Antrim"] },
  { name: "APEX", locations: ["London"] },
  { name: "Apollo Leeds", locations: ["Leeds"] },
  { name: "Apollo Trampoline Club", locations: ["Washington"] },
  { name: "Appley Bridge School of Gymnastics", locations: ["Chorley"] },
  { name: "Aquila Trampoline", locations: ["Swindon"] },
  { name: "Arabesque Gymnastics Limited", locations: ["Belfast"] },
  { name: "Arabian School of Gymnastics", locations: ["Milton Keynes"] },
  { name: "Arbroath", locations: ["Dundee"] },
  { name: "Arbroath GC", locations: ["Arbroath"] },
  { name: "Ascendance School of Gymnastics", locations: ["Downpatrick"] },
  { name: "ASG Community Gymnastics Club", locations: ["London", "Sidcup"] },
  { name: "Ashfield Gymnastics Club", locations: ["Nottingham", "Sutton in Ashfield"] },
  { name: "Ashmole Phoenix Gym Club", locations: ["Southgate"] },
  { name: "Ashton Gymnastics", locations: ["Tadcaster"] },
  { name: "Aspire Gymnastics Academy", locations: ["Romford"] },
  { name: "Aspire Gymnastics Club Hull", locations: ["Hull"] },
  { name: "Aspire Gymnastics NI", locations: ["Armagh"] },
  { name: "Astrid Academy of", locations: ["Spennymoor"] },
  { name: "Athena Gymnastics Academy", locations: ["Coulsdon"] },
  { name: "Athena Gymnastics Club", locations: ["Bexleyheath"] },
  { name: "Athena Sports Academy", locations: ["Newton Aycliffe"] },
  { name: "Atmosphere Trampoline Gymnastics", locations: ["Mansfield"] },
  { name: "Atmosphere Trampoline Gymnastics Academy", locations: ["Alfreton", "Kiveton Park"] },
  { name: "Attercliffe Gymnastics Academy", locations: ["Sheffield"] },
  { name: "Auchterarder", locations: ["Auchterarder"] },
  { name: "Aurora Gymnastics West", locations: ["London"] },
  { name: "AV Greenwich", locations: ["Bexleyheath", "London"] },
  { name: "AV Gymnastics Club", locations: ["Stockport"] },
  { name: "Avonbourne Gym", locations: ["Bournemouth"] },
  { name: "Avondale Acro GC", locations: ["Larkhall"] },
  { name: "Avondale Gym Club", locations: ["Surbiton"] },
  { name: "Axis Trampoline Club", locations: ["Bristol"] },
  { name: "Axminster Gymnastics", locations: ["Axminster"] },
  { name: "Ayrshire GC", locations: ["Kilmarnock"] },
  { name: "Back 2 Back Gymnastics Club", locations: ["Stone"] },
  { name: "Balance & Beam", locations: ["Stoke on Trent"] },
  { name: "Balanced Knights Gymnastics Club", locations: ["London"] },
  { name: "Balmoor", locations: ["Peterhead"] },
  { name: "Balwearie", locations: ["Kirkcaldy"] },
  { name: "Banchory Trampoline & DMT", locations: ["Banchory"] },
  { name: "Barnsley Community Gymnastics Academy", locations: ["Barnsley"] },
  { name: "Barnsley Premier Gymnastics", locations: ["Rotherham"] },
  { name: "Basildon", locations: ["Basildon"] },
  { name: "Basingstoke Gym", locations: ["Basingstoke"] },
  { name: "Bath Trampoline and Gym Academy", locations: ["Bath", "Bristol"] },
  { name: "BDR Gymnastics Club", locations: ["London"] },
  { name: "Be Distinct Gymnastics Academy", locations: ["LONDON"] },
  { name: "Be...Gymnastics", locations: ["Eastbourne"] },
  { name: "Beacon GC", locations: ["Aberdeen"] },
  { name: "Beacon Rhythmic GC", locations: ["Aberdeen"] },
  { name: "Beaming", locations: ["Gravesend", "Longfield"] },
  { name: "Bebington Gymnastics Club", locations: ["Wirral"] },
  { name: "Beccles Royales Gym Club", locations: ["Beccles"] },
  { name: "Beckenham Fliers Trampoline", locations: ["Beckenham"] },
  { name: "Bedford Flyers Tramp Club", locations: ["BEDFORD"] },
  { name: "Belfast Galaxy Trampoline & DMT Club enc Comet Kids", locations: ["Antrim", "Belfast", "N Newtownabbey"] },
  { name: "Believe Gymnastics Club", locations: ["Amersham"] },
  { name: "Belle Vue Trampoline Club", locations: ["Consett"] },
  { name: "Benchmark Gymnastics Club", locations: ["London"] },
  { name: "Berkhamsted Gymnastics Club", locations: ["Berkhamsted"] },
  { name: "Bevendean Gymnastics Club", locations: ["Brighton"] },
  { name: "Billings Rhythmic Gym", locations: ["Northampton"] },
  { name: "Bingham", locations: ["Nottingham"] },
  { name: "Birches Valley Gymnastics", locations: ["CANNOCK"] },
  { name: "Birkenhead Gymnastics Academy", locations: ["Birkenhead"] },
  { name: "Birkenhead Trampoline Club", locations: ["Birkenhead"] },
  { name: "Birmingham Bouncers", locations: ["Birmingham"] },
  { name: "Birmingham Flames O G C", locations: ["Birmingham"] },
  { name: "Birmingham Gymnastics Academy", locations: ["Birmingham"] },
  { name: "Birmingham Tornadoes Gymnastic Club", locations: ["Birmingham"] },
  { name: "Bishopbriggs Acro GC", locations: ["Glasgow"] },
  { name: "Blackburn with Darwen Acrobatic Gymnastic", locations: ["Blackburn"] },
  { name: "Blackfen Gym Club", locations: ["Sidcup"] },
  { name: "Blackpool Tiggers", locations: ["Blackpool"] },
  { name: "Blandford Forum Gymnastics Club", locations: ["Blandford Forum"] },
  { name: "Bolton Gymnastics Club", locations: ["Bolton"] },
  { name: "Bolton Trampoline Gymnastics Academy", locations: ["Bolton"] },
  { name: "Booker Gym Club", locations: ["High Wycombe"] },
  { name: "Boost Trampolining CIC", locations: ["Weston-super-mare"] },
  { name: "Bounce DMT & Trampoline", locations: ["Sheerness"] },
  { name: "Bounce DMT & Trampoline Club", locations: ["Sheerness"] },
  { name: "Bouncing Stars", locations: ["Birmingham"] },
  { name: "Bourne 2 Bounce", locations: ["Christchurch"] },
  { name: "Bourne End Gymnastics Academy", locations: ["Bourne End"] },
  { name: "Bourne Gymnastics", locations: ["Sittingbourne"] },
  { name: "Bourton Gymnastic Club", locations: ["Bourton-on-the-Water"] },
  { name: "Bracknell Gymnastics", locations: ["Bracknell"] },
  { name: "Bradford Gymnastic Club", locations: ["Bradford"] },
  { name: "Bradford Olympian T.C.", locations: ["Bradford"] },
  { name: "Bradworthy Gymnastics Club", locations: ["Bude"] },
  { name: "Brentwood Trampoline Club", locations: ["Brentwood"] },
  { name: "Bridge Gymnastics", locations: ["Enniskillen"] },
  { name: "Bridge Park Gymnastics Club", locations: ["London"] },
  { name: "Brighton Gymnastics", locations: ["Brighton"] },
  { name: "Bristol Hawks Gym Club", locations: ["Easton"] },
  { name: "Bristol School Of Gymnastics", locations: ["Bristol"] },
  { name: "Bristol Trampoline and Gymnastics", locations: ["BRISTOL"] },
  { name: "Broadland Gymnastics Club", locations: ["Great Yarmouth"] },
  { name: "Bromley Valley Gymnastics", locations: ["Orpington"] },
  { name: "Bromsgrove Gymnastics Club", locations: ["Bromsgrove"] },
  { name: "Brumby Gymnastic Club", locations: ["Scunthorpe"] },
  { name: "Bucks Trampoline and Tumbling Academy (BTTA)", locations: ["Wendover"] },
  { name: "Bulmershe Gym", locations: ["Reading"] },
  { name: "Bury Gymnastics", locations: ["Bury"] },
  { name: "Bury Spectrum Gym", locations: ["Bury St. Edmunds"] },
  { name: "Bury Trampoline Club", locations: ["Bury"] },
  { name: "Busybodz Gymnastics", locations: ["Droylsden"] },
  { name: "C C", locations: ["Stockport"] },
  { name: "Cacl Gym Club Eastbourne", locations: ["Eastbourne", "Hailsham"] },
  { name: "Cage Service Ltd", locations: ["Waterlooville"] },
  { name: "Caithness GC", locations: ["Thurso"] },
  { name: "Calverton Gymnastics Club", locations: ["Calverton"] },
  { name: "Cambourne Comets Trampoline Club", locations: ["Cambridge"] },
  { name: "Cambridge Cangaroos", locations: ["Cambridge"] },
  { name: "Cambridge Gymnastics", locations: ["Cambridge"] },
  { name: "Cambridge University Gymnastics Club", locations: ["Bury St. Edmunds", "Cambridge", "Huntingdon", "Milton Keynes", "Stevenage"] },
  { name: "Cambridge University Trampoline", locations: ["Cambridge"] },
  { name: "Camden Gymnastics", locations: ["London"] },
  { name: "Cameo GC", locations: ["Coatbridge"] },
  { name: "Canterbury Rhythmic Gymnastics Ltd", locations: ["Ashford Kent", "Canterbury"] },
  { name: "Carlisle Gymnastics Club", locations: ["Carlisle"] },
  { name: "Carlisle Trampoline Club", locations: ["Carlisle"] },
  { name: "Carnegie Spartan GC", locations: ["Dunfermline"] },
  { name: "Carousel School Of Gymnastics", locations: ["Rochford", "Wickford"] },
  { name: "Carterton Gymnastics Club CIC", locations: ["Carterton"] },
  { name: "Cartwheels Pre-School Gymnastics", locations: ["Harrow", "Loughton", "North Weald", "Northwood"] },
  { name: "Castle Gymnastics", locations: ["Kenilworth"] },
  { name: "Castle Rhythmic Gym Club", locations: ["Bangor"] },
  { name: "Caterham Gymnastics Academy", locations: ["CATERHAM", "Caterham"] },
  { name: "Celebrate Gymnastics Club", locations: ["Billericay"] },
  { name: "Central Galaxy Coventry Trampoline", locations: ["Coventry"] },
  { name: "Central Gymnastics Academy Unit 3 2 Unit Munro Road", locations: ["FK7 7UU"] },
  { name: "Centrum Gymnastics Ltd", locations: ["London"] },
  { name: "CGA Gymnastics", locations: ["Cambridge", "Ely"] },
  { name: "CGC Leisure", locations: ["Canterbury"] },
  { name: "Chalfont Gymnastics Academy Limited", locations: ["GERRARDS CROSS"] },
  { name: "Charnwood Trampoline Club", locations: ["COALVILLE", "Loughborough"] },
  { name: "Cheam Gymnastics Club", locations: ["Sutton"] },
  { name: "Cheam Trampoline Club", locations: ["Cheam"] },
  { name: "Checkers Gymnastic", locations: ["Gloucester"] },
  { name: "Chelmsford Gym Club", locations: ["Chelmsford"] },
  { name: "Cheltenham Academy of Acrobatic Gymnastics", locations: ["Gloucester"] },
  { name: "Cheltenham and Gloucester Gymnastics Club", locations: ["Gloucester"] },
  { name: "Chesterfield Gymnastics & Trampolining Academy", locations: ["Chesterfield"] },
  { name: "Chichester Gymnastics Academy", locations: ["CHICHESTER"] },
  { name: "Chippenham Moonraker Gymnastics", locations: ["Corsham"] },
  { name: "City of Aberdeen", locations: ["ABERDEEN", "Aberdeen"] },
  { name: "City of Birmingham Gym Club", locations: ["Birmingham"] },
  { name: "City of Coventry Trampoline & Gymnastic Club", locations: ["Coventry"] },
  { name: "City of Edinburgh GC", locations: ["Edinburgh"] },
  { name: "City of Edinburgh Trampoline Club", locations: ["Bonnyrigg", "Tranent"] },
  { name: "City of Glasgow GC", locations: ["Glasgow"] },
  { name: "City of Lancaster Gymnastics Club", locations: ["Lancaster"] },
  { name: "City of Lisburn Salto National Gym Centre", locations: ["Lisburn"] },
  { name: "City Of Liverpool Gym Club", locations: ["Liverpool"] },
  { name: "City Of Manchester Institute Of Gymnastics", locations: ["Gorton"] },
  { name: "City of Manchester Rhythmic Academy", locations: ["Manchester"] },
  { name: "City of Newcastle Gym Academy", locations: ["Newcastle Upon Tyne"] },
  { name: "City of Plymouth Trampoline and Gymnastics", locations: ["Plymouth"] },
  { name: "City of Preston Gymnastics Club", locations: ["Preston"] },
  { name: "City Of Salford Gym Club", locations: ["Salford"] },
  { name: "City Of Salford Trampoline", locations: ["Salford"] },
  { name: "City of Salisbury Gymnastics Club", locations: ["Salisbury"] },
  { name: "City Of Sheffield", locations: ["Sheffield"] },
  { name: "City of Stoke Acrobatics Gymnastics", locations: ["Stoke-on-Trent"] },
  { name: "City Of Worcester Gymnastics Club", locations: ["Malvern", "Worcester"] },
  { name: "Clevedon Gymnastics Centre", locations: ["Clevedon"] },
  { name: "Club GymFun", locations: ["N Newtownabbey"] },
  { name: "Clyde Valley Gymnastics Club", locations: ["Dumbarton"] },
  { name: "Coalville Gym Club", locations: ["Coalville"] },
  { name: "Colchester Gymnastics Club", locations: ["Colchester"] },
  { name: "Comberton Gymnastics", locations: ["Cambridge"] },
  { name: "Community Gymnastics", locations: ["Halifax"] },
  { name: "Coney Hall Cosmonauts", locations: ["Bromley"] },
  { name: "Corby Gymnastics", locations: ["Corby", "Northampton"] },
  { name: "Cornish Trampolining", locations: ["St. Austell"] },
  { name: "Cornwall Gymnastics Centre", locations: ["Wadebridge"] },
  { name: "Cosmos Trampoline Club", locations: ["Yate"] },
  { name: "Cotswold Gymnastics Club CASC", locations: ["Cirencester"] },
  { name: "Cottenham Gymnastics", locations: ["Histon"] },
  { name: "Cottenham Gymnastics Club", locations: ["Cambridge"] },
  { name: "Craven Gymnastics Club", locations: ["Skipton"] },
  { name: "Crewe & Nantwich Gym Club", locations: ["Crewe"] },
  { name: "Crossway Gymnastics Club", locations: ["London"] },
  { name: "Croydon Acro", locations: ["Coulsdon"] },
  { name: "Croydon Gymnastics Club", locations: ["Caterham Surrey", "Oxted"] },
  { name: "Crystal Palace Gymnastics Club", locations: ["London"] },
  { name: "Cumbernauld GC", locations: ["Glasgow"] },
  { name: "D.P.S.A Gymnastics Club", locations: ["Daventry"] },
  { name: "Dako 'Flying Angels' Gym Club", locations: ["Sneinton"] },
  { name: "Dan Purvis Gymnastics", locations: ["Liverpool"] },
  { name: "Darlington Gymnastics Club", locations: ["Darlington"] },
  { name: "Dartford Gymnastics Club", locations: ["Dartford"] },
  { name: "Dartford Trampoline Club", locations: ["Dartford"] },
  { name: "Darwin Gymnastics and Dance", locations: ["Shrewsbury"] },
  { name: "DC", locations: ["Ashford", "Canterbury", "Folkestone"] },
  { name: "DC Gymnastics", locations: ["Berwick-upon-tweed"] },
  { name: "Deal Gym Club", locations: ["Deal"] },
  { name: "Deerness Gymnastics Club", locations: ["Durham"] },
  { name: "Delta", locations: ["Swindon"] },
  { name: "Delta Trampoline Club", locations: ["Derby"] },
  { name: "Derby City Gymnastics Club", locations: ["Derby"] },
  { name: "Derbyshire Gymnastics Academy", locations: ["Ripley"] },
  { name: "Derwent Valley Gymnastics Club", locations: ["consett"] },
  { name: "Devotion RGA Ltd", locations: ["London"] },
  { name: "Dexterity Gymnastics Club", locations: ["Beverley", "Hull"] },
  { name: "Dharma Gym for", locations: ["Aylesford", "Maidstone", "Tenterden"] },
  { name: "Diamond Gymnastics (Amersham)", locations: ["Amersham"] },
  { name: "Diamonds Gymnastic Club", locations: ["Halifax"] },
  { name: "Diamonds Trampoline & DMT", locations: ["Inverurie"] },
  { name: "Dimensions Trampoline", locations: ["Colchester"] },
  { name: "DKN", locations: ["Woodford Green"] },
  { name: "DLJ Gymnastics Club", locations: ["Gillingham"] },
  { name: "Dolphina Gym Club", locations: ["Watford"] },
  { name: "Doncaster Gymnastics", locations: ["Doncaster"] },
  { name: "Donside GC", locations: ["Inverurie"] },
  { name: "Dover Gym Club", locations: ["Dover"] },
  { name: "Dragons Trampoline Club", locations: ["Norwich"] },
  { name: "Drayton Gym Club", locations: ["Hanwell"] },
  { name: "Dreamweaver Gymnastics Club", locations: ["Cambridge"] },
  { name: "Dronfield Gymnastics", locations: ["Dronfield"] },
  { name: "Drumchapel GC", locations: ["Drumchapel"] },
  { name: "Dudley Gymnastics Club", locations: ["Brierley Hill"] },
  { name: "Dumfries Y Gymnastics", locations: ["Annan", "Dumfries"] },
  { name: "Dundee Gymnastics Club", locations: ["Dundee"] },
  { name: "Dundee Gymnastics Club 2k", locations: ["Dundee"] },
  { name: "Dundee Uni TC", locations: ["Dundee"] },
  { name: "Dundee University Gymnastics", locations: ["Dundee"] },
  { name: "Dundonald", locations: ["Ayr"] },
  { name: "Dunfermline Zodiak GC", locations: ["Dunfermline"] },
  { name: "Dungannon Gymnastics Club", locations: ["Dungannon"] },
  { name: "Durham City Gymnastics", locations: ["Durham"] },
  { name: "Dynamic Gymnastics Academy", locations: ["Motherwell"] },
  { name: "Dynamite GC", locations: ["Clydebank"] },
  { name: "Dynamix Gymnastics Club", locations: ["Braintree"] },
  { name: "Dynamo School Of Gymnastics", locations: ["Southampton"] },
  { name: "Dyson Gymnastics Club", locations: ["Hove"] },
  { name: "E.J.B Gymnastics Club", locations: ["Amersham", "Borehamwood"] },
  { name: "Eagle GC", locations: ["Paisley"] },
  { name: "Eagles Acrobatic", locations: ["Kingsbridge"] },
  { name: "Eagles Gymnastics", locations: ["King's Lynn", "Wisbech"] },
  { name: "Ealing", locations: ["London"] },
  { name: "Earls Gymnastics Club", locations: ["Halesowen", "Oldbury"] },
  { name: "East Kent Acro Gym Club", locations: ["Deal"] },
  { name: "East Kilbride GC", locations: ["East Kilbride"] },
  { name: "East London Gym Club", locations: ["LONDON"] },
  { name: "East Lothian Gymnastics Academy", locations: ["Prestonpans"] },
  { name: "East Staffs Gym Club", locations: ["Burton-on-Trent"] },
  { name: "East Surrey Acrobatics", locations: ["Redhill", "Reigate"] },
  { name: "Easton Gymnastics Club", locations: ["Norwich"] },
  { name: "Ecco Gymnastics", locations: ["Sheffield"] },
  { name: "Eclipse Gymnastics", locations: ["Fareham", "Grimsby", "Southampton"] },
  { name: "Eclipse Gymnastics Club", locations: ["Oldham"] },
  { name: "Eclipse Gymnastics Club (East Mids)", locations: ["Rushden"] },
  { name: "Eclipse Gymnastics Club Scotland", locations: ["Aberdeen"] },
  { name: "Edgbarrow Trampoline", locations: ["Bracknell"] },
  { name: "Edge Acrobatic", locations: ["Glastonbury", "Street"] },
  { name: "Edge Hill Sport Gymnastics", locations: ["Ormskirk"] },
  { name: "Edinburgh University", locations: ["Dalkeith", "Edinburgh"] },
  { name: "Edinburgh University Trampoline", locations: ["Edinburgh"] },
  { name: "Elements", locations: ["Dartford", "Gravesend"] },
  { name: "Elements Acro", locations: ["Shrewsbury"] },
  { name: "Elevate Acro Gymnastics", locations: ["Larkhall", "Livingston"] },
  { name: "Elevate Elite CIC", locations: ["Loughborough"] },
  { name: "ELITE GYM CLUB", locations: ["Barnet", "LONDON"] },
  { name: "Elite Gymnastics", locations: ["Antrim"] },
  { name: "Ellan Vannin Gymnastics Club", locations: ["Douglas"] },
  { name: "Ellastics Gymnastics Club", locations: ["Horley", "Redhill"] },
  { name: "Ellesmere Port Club of Gymnastics", locations: ["Ellesmere Port"] },
  { name: "Elmfield Gymnastics Club", locations: ["Doncaster"] },
  { name: "Embrace Gymnastics Performance", locations: ["Wigan"] },
  { name: "Emmer Green Gymnastics", locations: ["Reading"] },
  { name: "Empower Gymnastics Club", locations: ["Mansfield"] },
  { name: "Enderby Olympic Gym Club", locations: ["Enderby"] },
  { name: "Enigma GC", locations: ["Leven"] },
  { name: "Epping Gymnastics Club", locations: ["Epping"] },
  { name: "EPTC", locations: ["Nottingham"] },
  { name: "Erewash Valley Gym Club", locations: ["Ilkeston", "Nottingham"] },
  { name: "ESG Academy", locations: ["Borehamwood", "Potters Bar"] },
  { name: "Esprit", locations: ["Swindon"] },
  { name: "Esprit Rhythmic Gymnastics Club", locations: ["Swindon"] },
  { name: "Europa Gym Centre CIC", locations: ["Crayford"] },
  { name: "Everton Park Gymnastics Club", locations: ["Liverpool"] },
  { name: "Evoke Gymnastics", locations: ["Swindon"] },
  { name: "Evolution Rhythmic Gymnastics Academy", locations: ["London"] },
  { name: "Evolution Trampoline Club", locations: ["Frome", "Warminster"] },
  { name: "Evolve Gymnastics Academy", locations: ["Manchester"] },
  { name: "Evolve Gymnastics Club (Scotland)", locations: ["Glasgow"] },
  { name: "EVT Gymnastics", locations: ["Nottingham"] },
  { name: "Exeter Gym Club", locations: ["Exeter"] },
  { name: "Exeter Trampoline", locations: ["Exeter"] },
  { name: "Extension Gymnastics", locations: ["Tonbridge"] },
  { name: "Extreme Trampoline Club", locations: ["Nottingham"] },
  { name: "Falcon S A Gym Club", locations: ["Bedford"] },
  { name: "Falcon Spartak Gym Club", locations: ["Sidcup"] },
  { name: "Falcons Gym", locations: ["Barnstaple"] },
  { name: "Falkirk School of Gymnastics", locations: ["Falkirk"] },
  { name: "Fareham School Of Gym", locations: ["Fareham"] },
  { name: "Farnborough Flyers", locations: ["Aldershot Hampshire"] },
  { name: "Fash Gym Club", locations: ["Chislehurst"] },
  { name: "Faversham Gymnastics Club", locations: ["Faversham"] },
  { name: "Fenland Gymnastics", locations: ["Wisbech"] },
  { name: "Fife GC", locations: ["Dunfermline"] },
  { name: "Finesse Rhythmic Gymnastics Club", locations: ["Speke", "St Helens"] },
  { name: "Five Gymnastics", locations: ["London"] },
  { name: "Flair", locations: ["Glasgow"] },
  { name: "Flare Gymnastics", locations: ["Southampton"] },
  { name: "Flex & Flip Gymnastics", locations: ["Biggleswade"] },
  { name: "Flex Gymnastics Club", locations: ["Petersfield"] },
  { name: "Flexx Gymnastics Club Reading", locations: ["Reading"] },
  { name: "Flic Flac GC", locations: ["St. Andrews"] },
  { name: "Flight Gymnastics", locations: ["N Newtownabbey"] },
  { name: "Flight Trampoline Club", locations: ["Harlow"] },
  { name: "Flip & Twist Acro", locations: ["Stonehouse"] },
  { name: "Flipping Out Gymnastics", locations: ["Birmingham"] },
  { name: "Flips Gymnastics Club", locations: ["Hatfield"] },
  { name: "Flitecrew Trampoline Club", locations: ["Crawley", "Horsham"] },
  { name: "FLIX Gymnastics", locations: ["Bedford"] },
  { name: "Flow Gymnastics", locations: ["Banstead"] },
  { name: "Flyers TC", locations: ["Glenrothes"] },
  { name: "Flying Angels Gymnastics", locations: ["London"] },
  { name: "Flyte Gymnastics", locations: ["Coventry"] },
  { name: "Forest Of Dean Gymnastics Club", locations: ["Coleford"] },
  { name: "Forres", locations: ["Forres"] },
  { name: "Forth Valley Team Gymnastics", locations: ["Larbert"] },
  { name: "Fox Gymnastics Club", locations: ["Farnborough"] },
  { name: "Framtastics Gym Club", locations: ["Norwich"] },
  { name: "Freedom", locations: ["Beckenham", "Bromley", "Croydon"] },
  { name: "Fromeside Gymnastics", locations: ["Bristol"] },
  { name: "Fuego Gymnastics", locations: ["Newick"] },
  { name: "Furness Gymnastics Club", locations: ["Barrow-In-Furness"] },
  { name: "Fusion", locations: ["Birmingham"] },
  { name: "Futunity UK Gymnastics Club", locations: ["Uxbridge"] },
  { name: "Fylde Coast Rhythmic Gymnastic", locations: ["Preston"] },
  { name: "Fyrish GC", locations: ["Alness"] },
  { name: "G’s Gymnastics Academy", locations: ["Lydney"] },
  { name: "Gaia Gymnastics &", locations: ["Westbury"] },
  { name: "Galaxy Rhythmic Gymnastics Club", locations: ["Lytham St. Annes"] },
  { name: "Galaxy Stars Trampoline Club", locations: ["Aylesford"] },
  { name: "Garioch GC", locations: ["Alford", "Ellon", "Insch", "Inverurie"] },
  { name: "Gazelles Gym Club", locations: ["Redruth"] },
  { name: "Gemini Gym Club", locations: ["Nailsea", "Westerham"] },
  { name: "Gemini Gymnastics Club", locations: ["Loughton"] },
  { name: "Generation Gymnastics", locations: ["Camberley"] },
  { name: "Genesis Gymnastics", locations: ["Chessington"] },
  { name: "Giants Gymnastics Company", locations: ["Littlehampton"] },
  { name: "Gibraltar Gymnastics Club", locations: ["Gibraltar"] },
  { name: "Glasgow Gymnastics", locations: ["Glasgow"] },
  { name: "Glasgow Uni", locations: ["Glasgow"] },
  { name: "Glossop Gymnastics Club", locations: ["Glossop"] },
  { name: "Gloucester Gymnastics Club", locations: ["Cheltenham"] },
  { name: "Goldring’s Gymnastics", locations: ["Sherborne"] },
  { name: "Goole Gymnastics Club", locations: ["Goole"] },
  { name: "Goshawks Gym", locations: ["Gosport"] },
  { name: "GR8", locations: ["Warrington"] },
  { name: "Grace Gymnastics School", locations: ["London"] },
  { name: "Grantham Gym", locations: ["Grantham"] },
  { name: "Gravitate Trampoline Club", locations: ["Telford"] },
  { name: "Greater Manchester Trampoline Gymnastics Academy", locations: ["Bury"] },
  { name: "Greenhead Gym", locations: ["Huddersfield"] },
  { name: "Greenhill Gymnastics Club", locations: ["Herne Bay"] },
  { name: "Greenwich Royals Gymnastics Club", locations: ["London"] },
  { name: "Griffin Association Gymnastics and Trampolining", locations: ["Street"] },
  { name: "Griffin Gymnastics", locations: ["Harlow"] },
  { name: "Grimsby & District School of", locations: ["Grimsby"] },
  { name: "Grimsby Twist & Flip Gymnastics Academy", locations: ["Grimsby"] },
  { name: "Grindon Gymnastics Club", locations: ["Sunderland"] },
  { name: "Grove & Didcot Gym Club", locations: ["Grove"] },
  { name: "Grundy Park Gym Club", locations: ["Cheshunt", "Maldon"] },
  { name: "Gryphon West Gym Club", locations: ["Sherborne", "Yeovil"] },
  { name: "GS Gymnastics", locations: ["Prudhoe"] },
  { name: "Guernsey Specials Gym Club LBG", locations: ["Guernsey"] },
  { name: "Guernsey Tumbling Centre", locations: ["Guernsey"] },
  { name: "Gym", locations: ["Edinburgh"] },
  { name: "Gym Mania", locations: ["Fleetwood"] },
  { name: "Gym Rox", locations: ["Brentwood", "Ingatestone"] },
  { name: "Gym Stars Gymnastics NI", locations: ["NEWRY"] },
  { name: "Gym Trix", locations: ["Newry"] },
  { name: "Gymco", locations: ["Worthing"] },
  { name: "Gymfinity Gymnastics Academy", locations: ["Altrincham", "Knutsford"] },
  { name: "Gymfinity Gymnastics Club", locations: ["Telford"] },
  { name: "Gymfit Gymnastics Club", locations: ["Epsom", "Ewell"] },
  { name: "Gymflix", locations: ["Beckenham"] },
  { name: "GymForce", locations: ["Stockport"] },
  { name: "GymMad Gymnastics Academy", locations: ["TS18 3TD"] },
  { name: "Gymmagic", locations: ["Pudsey"] },
  { name: "Gymnastics", locations: ["Bedford"] },
  { name: "Gymnastics &", locations: ["Southport"] },
  { name: "Gymnastics And Dance", locations: ["Manningtree"] },
  { name: "Gymnastics FM", locations: ["dagenham"] },
  { name: "Gymnastics Zone Ltd", locations: ["Leicester"] },
  { name: "Gymstars Gymnastics Academy", locations: ["Wimborne"] },
  { name: "Gymtastix", locations: ["Ellon", "Inverurie"] },
  { name: "Gymtopia Gymnastics CIO", locations: ["Newcastle Upon Tyne"] },
  { name: "Gymworld Gymnastics Club", locations: ["Middlesbrough"] },
  { name: "Gymzkool", locations: ["Preston", "Southport"] },
  { name: "Gyrus Olympic Gym", locations: ["Witham"] },
  { name: "Hadleigh Stars", locations: ["Ipswich"] },
  { name: "Halo Sparks Gymnastics", locations: ["Hereford"] },
  { name: "Hamilton GC", locations: ["Glasgow", "Hamilton"] },
  { name: "Hammersmith & Fulham School of Gymnastics", locations: ["London"] },
  { name: "Hammersmith Gymnastics Club", locations: ["London"] },
  { name: "Hampstead Gymnastics Club C.I.C", locations: ["London"] },
  { name: "Harefield Gymnastics & Dance", locations: ["Uxbridge"] },
  { name: "Harlequin Gym Squad", locations: ["Leighton Buzzard"] },
  { name: "Harlequin Gymnastics Club", locations: ["Romford"] },
  { name: "Harriers Acrobatic Gymnastics Club", locations: ["Bristol"] },
  { name: "Harrogate Gymnastics Club", locations: ["Harrogate"] },
  { name: "Harrow School Of Gym", locations: ["Harrow"] },
  { name: "Harrow Trampoline", locations: ["Edgware", "Harrow"] },
  { name: "Hart Gymnastics", locations: ["Fleet"] },
  { name: "Hartford School Of Gym", locations: ["Anderton"] },
  { name: "Hartlepool Gymnastics Club", locations: ["Hartlepool"] },
  { name: "Haverhill Gymnastics Club", locations: ["Haverhill"] },
  { name: "Havering Gymnastics", locations: ["Romford"] },
  { name: "Hawth Gymnastics", locations: ["Crawley"] },
  { name: "HBS", locations: ["Hitchin"] },
  { name: "Head Over Heels GC", locations: ["Glasgow"] },
  { name: "Head to Toe Gymnastics Club", locations: ["Banbridge"] },
  { name: "Heart of England Trampoline & DMT Club", locations: ["Solihull"] },
  { name: "Heathrow Aerobic Gymnastics", locations: ["Bromley", "Hounslow", "Rochester"] },
  { name: "Heathrow Gym", locations: ["Hounslow"] },
  { name: "Heights Trampoline & Gymnastics Club", locations: ["Abingdon"] },
  { name: "Hendon Gym Club", locations: ["London"] },
  { name: "Hereford Gymnastics Academy", locations: ["Hereford"] },
  { name: "Hertford Gymnastics Academy", locations: ["Ware"] },
  { name: "Hetton Gymnastics Club", locations: ["Houghton Le Spring"] },
  { name: "Hexham Gymnastic Club", locations: ["Hexham"] },
  { name: "Heywood Sparks Gymnastics Academy", locations: ["Heywood"] },
  { name: "HGC", locations: ["Hoddesdon"] },
  { name: "Hi-tension Trampoline", locations: ["Colchester"] },
  { name: "High Green Gymnastics Academy", locations: ["Sheffield"] },
  { name: "High Springers Trampoline & Gymnastics Club", locations: ["Bushey"] },
  { name: "Highgate Newtown Gymnastics Club", locations: ["London"] },
  { name: "Hillfoots", locations: ["Alva"] },
  { name: "Hinckley & Burbage GC", locations: ["Hinckley"] },
  { name: "Hinckley Gymnastics Club", locations: ["Hinckley", "Leicester"] },
  { name: "Hinckley Trampoline Club", locations: ["Hinckley"] },
  { name: "HiTide Gymnastics Club", locations: ["Brighton"] },
  { name: "Holbeach And Fenland Gym Club", locations: ["Spalding"] },
  { name: "Holborn Gymnastics Club", locations: ["London"] },
  { name: "Hollington Gymnastics Club", locations: ["Hastings"] },
  { name: "Honiton Gymnastics Club", locations: ["Honiton"] },
  { name: "Hope Acrobatic Gymnastics Club", locations: ["St Helens"] },
  { name: "HoriZen Academy of Gymnastics", locations: ["Buntingford"] },
  { name: "Horizon", locations: ["Eastleigh", "Southampton"] },
  { name: "Hornsey 8-1 Trampoline", locations: ["London"] },
  { name: "Horsham Gymnastics Club", locations: ["Horsham"] },
  { name: "Huddersfield Trampoline Academy", locations: ["Huddersfield"] },
  { name: "Huntingdon Olympic Gymnastics Club", locations: ["Huntingdon"] },
  { name: "i-star Academy", locations: ["Shoreham by Sea"] },
  { name: "Ibex", locations: ["Bonnyrigg", "Edinburgh"] },
  { name: "Iceni Gymnastics", locations: ["Colchester"] },
  { name: "Iconix Gymnastics Club", locations: ["London"] },
  { name: "Idsall Gymnastics & Trampolining", locations: ["Newport", "Shifnal"] },
  { name: "Ilkley Gym", locations: ["Ilkley"] },
  { name: "Illusion GC", locations: ["Glasgow"] },
  { name: "Impulse Trampoline Club", locations: ["Dunmow"] },
  { name: "Inertia Gymnastics Academy", locations: ["Newry"] },
  { name: "Infinity Gymnastics", locations: ["Horsham"] },
  { name: "Innovate Gymnastics Club", locations: ["Callander", "Glasgow"] },
  { name: "Inspire Excellence", locations: ["Dagenham", "London", "Romford", "Woodford green"] },
  { name: "Inspire Gymnastics", locations: ["Salisbury"] },
  { name: "Inspire Gymnastics Academy", locations: ["Nottingham"] },
  { name: "Inspire Gymnastics Academy SCOTLAND", locations: ["Glasgow"] },
  { name: "Inverness GC", locations: ["Inverness"] },
  { name: "Inverness TC", locations: ["Inverness"] },
  { name: "Invert Gymnastics", locations: ["Birmingham"] },
  { name: "Inverurie Gymnastics Club", locations: ["Inverurie"] },
  { name: "Invictus Yorkshire Gymnastics", locations: ["Sheffield"] },
  { name: "Invoke Gymnastics Club", locations: ["Burntwood"] },
  { name: "Ipswich Four Trampoline Club", locations: ["Ipswich"] },
  { name: "Irvine Bay GC", locations: ["Irvine"] },
  { name: "Isle of Lewis GC", locations: ["Stornaway"] },
  { name: "Isle of Mull GC", locations: ["ISLE OF MULL", "Isle of Mull", "Oban"] },
  { name: "Ivybridge Gym Academy", locations: ["Ivybridge"] },
  { name: "J Star", locations: ["Salisbury"] },
  { name: "J21 Gymnastics Club", locations: ["Weston-Super-Mare"] },
  { name: "Jack Kane GC", locations: ["Edinburgh"] },
  { name: "Jaybee Gymnastics", locations: ["Hornchurch", "Rainham", "Romford"] },
  { name: "Jaybee Havering", locations: ["Hornchurch", "Romford"] },
  { name: "Jays Gymnastics", locations: ["Grays"] },
  { name: "Jersey Gymnastics", locations: ["Jersey"] },
  { name: "Jesters Gymnastics Club", locations: ["Pontefract"] },
  { name: "JGA", locations: ["Beckenham", "Bromley", "Chislehurst", "Croydon", "Eltham", "London", "Norwood", "Orpington", "West Wickham", "Westerham"] },
  { name: "JJ's Gymnastics Academy", locations: ["Pontefract"] },
  { name: "JNB Gymnastics Academy", locations: ["Stratford-upon-avon"] },
  { name: "Joe Fraser", locations: ["Lichfield"] },
  { name: "Jolly Gymnastics", locations: ["Hoveton", "Norwich"] },
  { name: "JS Gymnastics", locations: ["Evesham"] },
  { name: "JUMP GC", locations: ["Cumbernauld"] },
  { name: "Jump Trampoline", locations: ["Hailsham"] },
  { name: "Jump UK", locations: ["Leyland"] },
  { name: "Jumpers Trampoline Club", locations: ["Gillingham"] },
  { name: "Jumping Jacks", locations: ["Barnet"] },
  { name: "Junior Sport Stars School of", locations: ["Stockport"] },
  { name: "Jurassic", locations: ["Weymouth"] },
  { name: "Just Gymnastics", locations: ["Wilmslow"] },
  { name: "JymKidz", locations: ["N Newtownards"] },
  { name: "K-Squared Gymnastics", locations: ["Oxford"] },
  { name: "Kaboom Trampolining Club", locations: ["Beckenham"] },
  { name: "Kaleidoscope Gymnastics Cheer &", locations: ["Belfast"] },
  { name: "KC Gymnastics", locations: ["Glasgow"] },
  { name: "Kendal Gymnastics Club Ltd", locations: ["Kendal"] },
  { name: "Kennylands Gymnastics CIC", locations: ["Reading"] },
  { name: "Kensington & Chelsea Gymnastics Academy", locations: ["London"] },
  { name: "Kent College Gymnastic", locations: ["Tunbridge Wells"] },
  { name: "Kernow", locations: ["Newquay"] },
  { name: "Kestrel Acrobatics &", locations: ["Bristol"] },
  { name: "Kestrel Gymnastics", locations: ["Edinburgh"] },
  { name: "Kestrel Gymnastics Academy K.G.A", locations: ["Ashford"] },
  { name: "Kestrel Trampoline", locations: ["N Newtownards"] },
  { name: "Kettering Gymnastics", locations: ["Kettering"] },
  { name: "Kiani Gymnastics Academy", locations: ["Romford"] },
  { name: "Kilmarnock Acro GC", locations: ["Kilmarnock"] },
  { name: "King Edmund Acro", locations: ["Yate"] },
  { name: "Kingdom Gymnastics Trust", locations: ["Dunfermline"] },
  { name: "Kings Gymnastics Academy", locations: ["Bury St Edmunds", "Newmarket", "Norwich"] },
  { name: "Kings Hill Gymnastics Academy", locations: ["East Peckham"] },
  { name: "Kings Lynn Gymnastic Club", locations: ["King's Lynn"] },
  { name: "Kingsbridge Gymnastics", locations: ["Kingsbridge"] },
  { name: "Kingston GC", locations: ["GLASGOW", "Glasgow"] },
  { name: "Kingston Trampoline", locations: ["Chessington", "Kingston Upon Thames", "New Malden", "Walton on Thames"] },
  { name: "Kingston Vale Gym Club", locations: ["Loughborough"] },
  { name: "Kirkby Trampoline", locations: ["Kirkby in Ashfield"] },
  { name: "Kirkcaldy", locations: ["Kirkcaldy"] },
  { name: "Kirklees Rebound Tramp Club", locations: ["Huddersfield"] },
  { name: "Kirklees Trampoline Gymnastics", locations: ["huddersfield"] },
  { name: "Lace Hill Gymnastics Club", locations: ["Buckingham"] },
  { name: "Lady Hawkins Gymnastics Club", locations: ["Kington"] },
  { name: "Lala Yusifova Gymnastics Academy", locations: ["Brighton", "London"] },
  { name: "Largs", locations: ["Largs"] },
  { name: "Lasswade GC", locations: ["Bonnyrigg"] },
  { name: "Launchpad Trampoline Academy Hull", locations: ["Hull"] },
  { name: "Leamington and Warwick Gymnastics Club", locations: ["Leamington Spa"] },
  { name: "Leaps and Bounds Gymnastics Club Ltd", locations: ["Potters Bar"] },
  { name: "Leatherhead & Dorking Gym", locations: ["Leatherhead"] },
  { name: "Leeds Gymnastics Club", locations: ["Leeds"] },
  { name: "Legacy Gymnastics Club", locations: ["Inverkeithing"] },
  { name: "Lenzie Woodhead GC", locations: ["GLASGOW", "Glasgow"] },
  { name: "Levenmouth GC", locations: ["Levenmouth"] },
  { name: "Levitation", locations: ["Hemel Hempstead", "London"] },
  { name: "Liberty Gymnastics Club", locations: ["Camberley"] },
  { name: "Liberty Gymnastics Club (South West)", locations: ["Frome"] },
  { name: "Lifestyle Gymnastics Academy", locations: ["Ballymena"] },
  { name: "Lightning School of Gymnastics", locations: ["Sevenoaks"] },
  { name: "Lincoln City Gym Club", locations: ["Lincoln"] },
  { name: "Lincoln Gymnastics Club", locations: ["Lincoln"] },
  { name: "Lincoln Imps", locations: ["Lincoln"] },
  { name: "Lings Gymnastics Sports Academy", locations: ["Northampton"] },
  { name: "Links Gymnastics (Berkshire) Ltd", locations: ["Ascot", "Windsor"] },
  { name: "Linlithgow School of Gymnastics", locations: ["Linlithgow"] },
  { name: "Little Socks Gymnastics", locations: ["London"] },
  { name: "Littledown Gymnastics Club", locations: ["Bournemouth"] },
  { name: "Liverpool Trampoline Gymnastics Academy", locations: ["Liverpool"] },
  { name: "LJ Dance & Gymnastics (LJ D&G)", locations: ["Chorley", "Leyland"] },
  { name: "LK Aerobic Gymnastics", locations: ["Rufford", "Southport"] },
  { name: "London Borough of Hillingdon Gymnastics Club", locations: ["Hayes"] },
  { name: "London Falcons Trampoline Club", locations: ["London"] },
  { name: "London Gymnastics School of", locations: ["London"] },
  { name: "London Sport Academy", locations: ["London"] },
  { name: "London Trampoline Academy and London DMT", locations: ["Isleworth", "London"] },
  { name: "Long Eaton", locations: ["Nottingham"] },
  { name: "Longridge Gymnastics Club", locations: ["Preston"] },
  { name: "Lothian Springers TC", locations: ["Edinburgh"] },
  { name: "Loughborough Acrobatics Gymnastics Club", locations: ["Loughborough"] },
  { name: "Loughborough Gymnastics", locations: ["Loughborough"] },
  { name: "LS Gymnastics Crewe Academy", locations: ["Crewe"] },
  { name: "Luminites Gymnastics", locations: ["West Wickham"] },
  { name: "Lunar GC", locations: ["Lanark"] },
  { name: "Luton Gymnastics", locations: ["Luton"] },
  { name: "LX Community Gymnastics Centre CIC", locations: ["Belfast"] },
  { name: "LX Gymnastics Club", locations: ["Belfast"] },
  { name: "Lynx Aylesbury", locations: ["Aylesbury"] },
  { name: "M.A.B Gymnastics Club", locations: ["Northampton"] },
  { name: "Macclesfield T. Club", locations: ["Macclesfield", "Wilmslow"] },
  { name: "Macduff", locations: ["Montrose"] },
  { name: "Maidstone Gym Club", locations: ["Maidstone"] },
  { name: "Majestic Gymnastics", locations: ["Bristol"] },
  { name: "Manchester Academy of", locations: ["Salford"] },
  { name: "Mansfield Olympic Gym", locations: ["Mansfield"] },
  { name: "Manx Gym Centre Of Excellence", locations: ["Douglas"] },
  { name: "Market Harborough Trampoline Academy", locations: ["Market Harborough"] },
  { name: "Marriotts Gymnastics Club", locations: ["Stevenage"] },
  { name: "Marshside Gymnastics Club", locations: ["Southport"] },
  { name: "Matrix Gymnastics Academy", locations: ["Wellingborough"] },
  { name: "Max Force", locations: ["Dorking", "Tadworth", "Wallington"] },
  { name: "Mayfield Gymnastics Club", locations: ["London"] },
  { name: "Meadowbank GC", locations: ["Dalkeith"] },
  { name: "Meridian Gym", locations: ["Beverley"] },
  { name: "Meridian Gymnastics", locations: ["Yaxley"] },
  { name: "Merton Gymnastics Club", locations: ["Mitcham"] },
  { name: "Mid Suffolk Gymnastics Club", locations: ["Stowmarket"] },
  { name: "Middlebeck Gymnastics Club", locations: ["Newark"] },
  { name: "Middleton Gymnastics Club", locations: ["Middleton"] },
  { name: "Midlands Gymnastics Academy", locations: ["Nuneaton"] },
  { name: "Midlothian GC", locations: ["Bonnyrigg", "Midlothian"] },
  { name: "Milton Keynes Gym", locations: ["Milton Keynes"] },
  { name: "Milton Keynes Trampoline & DMT Academy", locations: ["Milton Keynes"] },
  { name: "Minra Gymnastics", locations: ["BIRMINGHAM", "Brentford", "Ormskirk", "Skelmersdale", "Willenhall"] },
  { name: "Momentum", locations: ["Kidderminster", "Tenbury Wells"] },
  { name: "Monarchs Sports Acro Club", locations: ["Highbridge"] },
  { name: "Monkton", locations: ["Millom"] },
  { name: "Monkton Gymnastics Club", locations: ["Jarrow"] },
  { name: "Mulbarton Gymnastic Club", locations: ["Norwich"] },
  { name: "Muswell Hill Rhythmic Gymnastics", locations: ["London"] },
  { name: "N C A A C Gymnastics", locations: ["Northampton"] },
  { name: "N&D Gymnastics Club", locations: ["Glasgow"] },
  { name: "Nemo's", locations: ["Oxford"] },
  { name: "Nemo's Gymnastics", locations: ["Witney"] },
  { name: "Nene Valley R G", locations: ["Kettering", "Northampton", "Wellingborough"] },
  { name: "New Ash Green Gymnastics", locations: ["Longfield"] },
  { name: "New Forest Aerobic Gymnastics", locations: ["Southampton"] },
  { name: "New Forest Gymnastics Club", locations: ["Lymington"] },
  { name: "New Horizon Gymnastics", locations: ["SALISBURY", "Shaftesbury"] },
  { name: "Newry Olympic Gymnastics Club", locations: ["Newry"] },
  { name: "Newton Abbot", locations: ["Newton Abbot"] },
  { name: "Newton Mearns Gymnastics Club", locations: ["Glasgow"] },
  { name: "Newtown Gymnastics", locations: ["Irvine"] },
  { name: "Nidderdale Gymnastics", locations: ["Harrogate", "Ripon"] },
  { name: "Night Flyers Trampoline Club", locations: ["Nottingham"] },
  { name: "Nile Wilson Gymnastics Academy", locations: ["London"] },
  { name: "Nile Wilson Gymnastics Burnley", locations: ["Burnley"] },
  { name: "Nile Wilson Gymnastics Coventry", locations: ["Coventry"] },
  { name: "Nile Wilson Gymnastics Leeds", locations: ["Leeds"] },
  { name: "Nile Wilson Gymnastics Mansfield", locations: ["Mansfield"] },
  { name: "Nile Wilson Gymnastics Rotherham", locations: ["Rotherham"] },
  { name: "Nile Wilson Gymnastics Wirral", locations: ["Wirral"] },
  { name: "Nile Wilson Gymnastics Wolverhampton", locations: ["Wolverhampton"] },
  { name: "Nitro Gymnastics and Trampolining", locations: ["Beckenham", "West Wickham"] },
  { name: "Normanton Sports Acro", locations: ["Normanton"] },
  { name: "North Apex Gymnastics", locations: ["Wick Caithness"] },
  { name: "North Birmingham Community Gymnastics", locations: ["Sutton Coldfield"] },
  { name: "North Devon Display G C", locations: ["Bideford"] },
  { name: "North Down Trampoline Academy", locations: ["Bangor"] },
  { name: "North East Gymnastics Academy", locations: ["Newcastle Upon Tyne"] },
  { name: "North East Gymnastics Centre", locations: ["Banff", "Ellon", "Inverurie"] },
  { name: "North Kirklees Special Gymnastic Club", locations: ["Batley"] },
  { name: "North Lakes Gymnastics", locations: ["Penrith"] },
  { name: "North Leeds Gymnastics Academy Community Club", locations: ["Boston Spa Wetherby"] },
  { name: "North London Gymnastics Club", locations: ["Edgware", "London", "Stanmore"] },
  { name: "North London Rhythmic Gymnastics Academy", locations: ["London"] },
  { name: "North Northants Gym Club", locations: ["Kettering"] },
  { name: "North Oxford Gymnastics", locations: ["Witney"] },
  { name: "North Staffordshire Trampolining", locations: ["Newcastle-under-Lyme", "Stoke On Trent"] },
  { name: "North Star Gymnastics", locations: ["Huddersfield"] },
  { name: "North Star Trampoline Club", locations: ["Newcastle Upon Tyne"] },
  { name: "North Walsham Gymnastics", locations: ["North Walsham"] },
  { name: "Northampton Gymnastics Academy", locations: ["Northampton"] },
  { name: "Northampton School of Rhythmic Gymnastics", locations: ["Northampton"] },
  { name: "Northamptonshire Trampoline Gymnastics Academy", locations: ["Moulton Park"] },
  { name: "Northern Hope Gym", locations: ["Birtley"] },
  { name: "Northwood Gymnastics", locations: ["Northwood"] },
  { name: "Norwich Gymnastics Club", locations: ["Norwich"] },
  { name: "Nottingham City", locations: ["Nottingham"] },
  { name: "Nottingham City Gymnastics", locations: ["Nottingham"] },
  { name: "Notts Gymnastics", locations: ["Nottingham"] },
  { name: "Nova Gymnastics Academy", locations: ["NEW MILTON", "New Milton"] },
  { name: "Number 1 Gymnastic Club CIC Ltd", locations: ["Minehead"] },
  { name: "Nuneaton Gymnastics Club", locations: ["Nuneaton"] },
  { name: "O.K Gymnastics", locations: ["London"] },
  { name: "O'Neills Gymnastics", locations: ["Belfast"] },
  { name: "Oadby & Leicester Gymnastics", locations: ["Leicester", "Market Harborough"] },
  { name: "Oakham Artistic Gymnastic", locations: ["Oakham"] },
  { name: "Okehampton Flyers Gym, Trampoline & DMT Club", locations: ["Holsworthy", "Okehampton"] },
  { name: "Oldham Central Trampoline Club", locations: ["Manchester"] },
  { name: "One More Gymnastics", locations: ["Northallerton"] },
  { name: "One Step Rhythmic Gymnastics Club", locations: ["Blackpool"] },
  { name: "Orchard Gymnastics Club", locations: ["Armagh"] },
  { name: "Orkney Gymnastics Club", locations: ["Kirkwall"] },
  { name: "Orpington Gymnastic Club", locations: ["Orpington"] },
  { name: "Oxford Academy of Gymnastics", locations: ["Thame"] },
  { name: "Oxford Rhythmic", locations: ["Oxford"] },
  { name: "Oxford University Gym", locations: ["Oxford", "Wallingford"] },
  { name: "Oxford University Trampoline", locations: ["Oxford"] },
  { name: "P.H.D. Fundamentals", locations: ["Galashiels", "Peebles"] },
  { name: "P4G (Passion4Gymnastics)", locations: ["Blackburn", "Rossendale"] },
  { name: "Panache", locations: ["Batley"] },
  { name: "Paragon Gymnastics Academy", locations: ["Reddish"] },
  { name: "Park Elite Trampoline Club", locations: ["North Shields"] },
  { name: "Park Wrekin Gymnastics Club Ltd", locations: ["Telford"] },
  { name: "Peak! Gymnastics NI", locations: ["N Newtownards"] },
  { name: "Pegasus GC", locations: ["Dundee", "Newport On Tay", "Tayport"] },
  { name: "Pegasus Gymnastics", locations: ["Maidstone"] },
  { name: "Pegasus Trampoline Club", locations: ["Ipswich"] },
  { name: "Peninsula Trampoline Club", locations: ["N Newtownabbey", "N Newtownards"] },
  { name: "Penketh Gymnastics Club", locations: ["Warrington"] },
  { name: "Pennine Gymnastics CIC", locations: ["Holmfirth", "Huddersfield"] },
  { name: "Penrith Gymnastics Club", locations: ["Penrith"] },
  { name: "Penryn Gymnastics", locations: ["Penryn"] },
  { name: "Pentland GC", locations: ["Balerno", "Currie"] },
  { name: "Penzance Gym Club", locations: ["Penzance"] },
  { name: "Perfect 10", locations: ["Barking", "London"] },
  { name: "Perform Better Gymnastics Academy C.I.C.", locations: ["Enfield", "London"] },
  { name: "Performance Trampoline Gymnastics", locations: ["Lancing", "Worthing"] },
  { name: "Performers Gymnastics Academy", locations: ["Clacton-on-sea"] },
  { name: "Perth GC", locations: ["Perth"] },
  { name: "Peterborough Gymnastics Academy", locations: ["Peterborough"] },
  { name: "Phoenix (Forfar) GC", locations: ["Brechin", "Dundee", "Forfar"] },
  { name: "Phoenix Flyers", locations: ["London"] },
  { name: "Phoenix Gymnastics", locations: ["Camborne"] },
  { name: "Phoenix Gymnastics Academy", locations: ["Sheffield"] },
  { name: "Phoenix Gymnastics NI C.I.C", locations: ["Antrim", "Toomebridge"] },
  { name: "Phoenix High Flyers", locations: ["Pocklington"] },
  { name: "Phoenix Legends Gym", locations: ["Woodston"] },
  { name: "Phoenix Trampolining Club", locations: ["Langley"] },
  { name: "Phoenixwood Gymnastics Club", locations: ["Nottingham"] },
  { name: "Pinewood Gymnastics Club", locations: ["Wokingham"] },
  { name: "Pinnacle Trampoline", locations: ["Reading"] },
  { name: "Pipers Vale Gymnastics", locations: ["Ipswich"] },
  { name: "Pivotal", locations: ["Bourenmouth", "Bournemouth", "Christchurch"] },
  { name: "Pix Gymnastics Club", locations: ["Arlesey"] },
  { name: "Planet Gymnastics", locations: ["Derry/Londonderry", "Londonderry"] },
  { name: "Platinum Gymnastics Academy", locations: ["Benfleet"] },
  { name: "Plymouth Swallows School Of Gym", locations: ["Plymouth"] },
  { name: "Poise and Balance gymnastics club", locations: ["LONDON"] },
  { name: "Poise Gymnastics Club", locations: ["Crawley"] },
  { name: "Poole Gymnastics & Trampolining", locations: ["Poole"] },
  { name: "Port Regis Gym Club", locations: ["Shaftesbury"] },
  { name: "Portsmouth Gymnastics", locations: ["Portsmouth"] },
  { name: "Portsmouth School Of Gym", locations: ["Portsmouth"] },
  { name: "Portsmouth Trampoline Club", locations: ["Portsmouth"] },
  { name: "Power GT", locations: ["Birmingham"] },
  { name: "Precision Gymnastics", locations: ["Battersea", "London"] },
  { name: "Preston City Trampoline", locations: ["Preston"] },
  { name: "Prime Acrobatics Ltd", locations: ["Camberley", "Woking"] },
  { name: "Pro-Star Gymnastics Academy", locations: ["N Newtownards"] },
  { name: "Propulsion Trampolining Club", locations: ["Birkenhead"] },
  { name: "Putney Gymnastics Academy Ltd", locations: ["London"] },
  { name: "Pyramid Acro Gym Club", locations: ["Sneinton"] },
  { name: "Quayside Trampoline & Gym Club", locations: ["Bridgwater"] },
  { name: "Queens Gymnastics", locations: ["Bangor", "Holywood"] },
  { name: "Queensmead Trampoline Club", locations: ["South Ruislip"] },
  { name: "Raans Chiltern Gym", locations: ["Amersham"] },
  { name: "Rainbow Gym Club C.I.C", locations: ["Belfast"] },
  { name: "Ratae Gymnastic Club", locations: ["Leicester"] },
  { name: "Rathgael Gymnastics & Tumbling Club", locations: ["Bangor"] },
  { name: "Raven Valley Gym Club C.I.C", locations: ["STANLEY"] },
  { name: "React Trampoline & Gymnastics Club", locations: ["Hereford"] },
  { name: "Reading Trampoline Club", locations: ["Reading"] },
  { name: "Rebound Gymnastics", locations: ["Solihull"] },
  { name: "Recoil Trampoline Club", locations: ["Brentwood"] },
  { name: "Red Shoes", locations: ["Blackpool"] },
  { name: "Redcar Gymnastics and Sports Club", locations: ["Redcar"] },
  { name: "Redhill & Reigate Gym Club", locations: ["Redhill"] },
  { name: "Regis Gymnastics Club", locations: ["Bognor Regis"] },
  { name: "Retford Gymnastics Club", locations: ["Retford"] },
  { name: "Revolution Gymnastics Club", locations: ["Birmingham"] },
  { name: "Revolve Trampoline Club", locations: ["Beckenham", "LONDON", "Westerham"] },
  { name: "RG1", locations: ["Reading"] },
  { name: "RGC Dynamo", locations: ["London"] },
  { name: "Rhythmic Excellence", locations: ["London"] },
  { name: "Rhythmic Gymnastics Academy", locations: ["Cobham"] },
  { name: "Rhythmic Gymnastics Club Worcester", locations: ["Worcester"] },
  { name: "Rhythmic Gymnastics School “Inspiration”", locations: ["Bournemouth"] },
  { name: "Rhythmic Sparks", locations: ["Angmering"] },
  { name: "Rib Valley Gymnastics", locations: ["Buntingford"] },
  { name: "Richards Trampoline Club", locations: ["Letchworth"] },
  { name: "Richmond Gymnastics Assoc.", locations: ["Hampton Hill", "Richmond", "Twickenham"] },
  { name: "Richmondshire Thirsk Dales", locations: ["Catterick Garrison", "Middlesbrough", "Thirsk"] },
  { name: "Rickmansworth", locations: ["Banbury"] },
  { name: "Rickmansworth Gymnastics", locations: ["Rickmansworth"] },
  { name: "Ripon Gymnastics Academy", locations: ["Knaresborough", "Ripon", "York"] },
  { name: "Rising Phoenix Gymnastics", locations: ["Nantwich"] },
  { name: "Riverside Gymnastics Academy", locations: ["London"] },
  { name: "RiversMeet Gymnastics Club", locations: ["Gillingham"] },
  { name: "Robert Atkinson Gym Club", locations: ["Thornaby"] },
  { name: "Robin Hood Gymnastics", locations: ["LEICESTER", "NOTTINGHAM", "Nottingham"] },
  { name: "Rochdale Olympic Gym Club", locations: ["Rochdale"] },
  { name: "Rock Steady Crew Tramp Club", locations: ["Croydon"] },
  { name: "Rotate Gymnastics", locations: ["Potters Bar"] },
  { name: "Rotations", locations: ["Huntingdon"] },
  { name: "Rotherham Sports Acro Club", locations: ["Rotherham"] },
  { name: "Rothwell", locations: ["Leeds"] },
  { name: "Rowan Gymnastics Club", locations: ["Cheltenham"] },
  { name: "Royal Navy Gymnastics Team", locations: ["Portsmouth", "Yeovil"] },
  { name: "Rugby Gymnastics", locations: ["Rugby"] },
  { name: "Rushmoor Gymnastics Academy", locations: ["Aldershot"] },
  { name: "SAADI Gymnastics Ltd", locations: ["Redbourn"] },
  { name: "Saltaire Gym Club", locations: ["Baildon"] },
  { name: "Saltire Team", locations: ["Dalkeith", "Edinburgh", "Eyemouth", "Tranent"] },
  { name: "Salto", locations: ["Dundee"] },
  { name: "Salto Gymnastics Club", locations: ["Luton"] },
  { name: "Sandbach Gymnastics", locations: ["Sandbach"] },
  { name: "Sandwell", locations: ["Wednesbury"] },
  { name: "Sansom School Of Fitness", locations: ["Portsmouth"] },
  { name: "Sapphire GC", locations: ["Glasgow"] },
  { name: "Sarah's Gymnastics School", locations: ["Gloucester"] },
  { name: "Sarah's Mini", locations: ["Sheffield"] },
  { name: "Sarnia Trampoline", locations: ["Guernsey"] },
  { name: "Sarnia Trampoline Club", locations: ["Guernsey"] },
  { name: "Scarborough Gym", locations: ["Scarborough"] },
  { name: "Scorpio Gymnastics Club", locations: ["Bo'ness"] },
  { name: "Scotia Trampoline Academy", locations: ["Paisley"] },
  { name: "Seaford Gymnastics Academy", locations: ["Newhaven"] },
  { name: "Seaham Gymnastics Club", locations: ["Seaham"] },
  { name: "Seaside Trampoline Academy", locations: ["Ferndown"] },
  { name: "Selby Swans Gymnastics Academy", locations: ["Selby"] },
  { name: "Setanta Fitness Gymnastics", locations: ["Armagh"] },
  { name: "Sevenoaks Royals", locations: ["Sevenoaks"] },
  { name: "Severn Gymnastics & Trampoline Club", locations: ["Shrewsbury"] },
  { name: "Severn Valley Gymnastics", locations: ["Gloucester"] },
  { name: "Shantallow Gymnastics", locations: ["Londonderry"] },
  { name: "Sharecroft Gymnastics", locations: ["Swadlincote"] },
  { name: "Sheer Velocity Tumbling Club", locations: ["Gloucester"] },
  { name: "Sheffield", locations: ["Sheffield"] },
  { name: "Sheffield All-Stars Gymnastics Academy", locations: ["Sheffield"] },
  { name: "Sheffield Elites Gymnastics Academy", locations: ["SHEFFIELD"] },
  { name: "Sheffield Performance Trampoline & Gymnastics Club", locations: ["Sheffield"] },
  { name: "Sheffield Trampoline Academy", locations: ["Sheffield"] },
  { name: "Shepton Mallet Gym", locations: ["Shepton Mallet"] },
  { name: "Sherburn Community Gymnastics", locations: ["Leeds"] },
  { name: "Sherwood Oaks Gymnastics Academy", locations: ["Sutton-in-ashfield"] },
  { name: "Shetland", locations: ["Shetland"] },
  { name: "Shine Acrobatic Gymnastics Club", locations: ["Barton-le-Clay"] },
  { name: "Shine Bright", locations: ["London"] },
  { name: "Shine Trampoline Club", locations: ["Aberdeen", "Inverurie"] },
  { name: "Shirley Gymnastics Club", locations: ["Croydon"] },
  { name: "Shooting Stars", locations: ["Telford"] },
  { name: "Shooting Stars Gym Ltd", locations: ["Brighton", "Hassocks", "Henfield", "Hove", "Lewes", "Pulborough", "Worthing"] },
  { name: "Shooting Starz Gymnastics", locations: ["Londonderry"] },
  { name: "Shrewsbury Gymnastics Academy", locations: ["Newport", "Shrewsbury"] },
  { name: "Sika Gymnastics Club", locations: ["Coleraine"] },
  { name: "Silhouettes Rhythmic Gym", locations: ["Alton"] },
  { name: "Silk", locations: ["Macclesfield"] },
  { name: "Silverline Gymnastics Club", locations: ["South Croydon"] },
  { name: "SIMMSplitz", locations: ["Twickenham"] },
  { name: "Sittingbourne Swifts", locations: ["Gillingham", "Sittingbourne"] },
  { name: "Sky High Gymnastics", locations: ["Poole"] },
  { name: "Sky High Trampoline Gymnastics Academy", locations: ["Uckfield"] },
  { name: "Skybound", locations: ["Ashford Kent", "Benenden"] },
  { name: "Skyline Gymnastics", locations: ["Sheffield"] },
  { name: "Skyscrapers Trampoline", locations: ["Leeds"] },
  { name: "Skywalkers", locations: ["London"] },
  { name: "SLC Gymnastics and Trampolining", locations: ["Stafford"] },
  { name: "Sleaford Elite Gym Club", locations: ["Sleaford"] },
  { name: "Sleaford Gymnastics", locations: ["Sleaford"] },
  { name: "Smiles For", locations: ["Bacup"] },
  { name: "Soar Valley Trampoline Club", locations: ["Leicester"] },
  { name: "Sobell Trampoline Club", locations: ["London"] },
  { name: "Sokol Gymnastics Academy", locations: ["Castlewellan"] },
  { name: "Solent Gymnastics Club", locations: ["Havant"] },
  { name: "Solihull Olympic Gymnastics Club", locations: ["Solihull"] },
  { name: "Solway GC", locations: ["Dumfries"] },
  { name: "South Ayrshire GC", locations: ["Ayr"] },
  { name: "South Devon School Of Gym", locations: ["Paignton"] },
  { name: "South Essex Gymnastics Club", locations: ["Basildon"] },
  { name: "South Lanarkshire TC", locations: ["East Kilbride"] },
  { name: "South Shropshire Gymnastics Club", locations: ["Craven Arms Shropshire", "Ludlow"] },
  { name: "South Staffs Acrobatic", locations: ["Cannock"] },
  { name: "South Staffs Acrobatics", locations: ["Cannock"] },
  { name: "South Tyneside Gym Club", locations: ["South Shields"] },
  { name: "Southampton Gym", locations: ["Southampton"] },
  { name: "Southampton Trampoline Club", locations: ["Eastleigh"] },
  { name: "Southbourne Gymnastics Club", locations: ["Emsworth"] },
  { name: "Southport Gymnastics Club", locations: ["Southport"] },
  { name: "Sovereign", locations: ["Redhill"] },
  { name: "Space Athlete Birmingham", locations: ["Birmingham"] },
  { name: "Spalding & District Gymnastics", locations: ["Spalding"] },
  { name: "Sparkles Gymnastics Club", locations: ["Bracknell", "READING"] },
  { name: "Sparta Trampoline", locations: ["Glasgow"] },
  { name: "Spartac Gym", locations: ["Ormskirk"] },
  { name: "Spectrum", locations: ["Glasgow"] },
  { name: "Spectrum Gymnastics", locations: ["Lingfield"] },
  { name: "Spelthorne Gymnastics", locations: ["Sunbury-on-thames"] },
  { name: "Spiral Gymnastics Club", locations: ["Peterborough"] },
  { name: "Spire Heights Trampolining Club", locations: ["Salisbury"] },
  { name: "Spirit Gymnastics Academy", locations: ["Yeovil"] },
  { name: "Split Leaps", locations: ["Great Yarmouth"] },
  { name: "Splits & Flips Gymnastics", locations: ["Lurgan"] },
  { name: "Splitz Gym Club", locations: ["Weston-super-mare"] },
  { name: "Splitz Gymnastics Club- NI", locations: ["Enniskillen"] },
  { name: "Sponte Sua Gym", locations: ["London"] },
  { name: "Sportac", locations: ["Feltham"] },
  { name: "Sports Club", locations: ["Newcastle Upon Tyne"] },
  { name: "Spring Boxx", locations: ["Malvern"] },
  { name: "Spring Gymnastics Community", locations: ["Norwich"] },
  { name: "SPRINGBOX", locations: ["HENLEY-ON-THAMES", "Wallingford"] },
  { name: "Springers Trampolining Club", locations: ["Liverpool"] },
  { name: "Springfield Trampoline Academy", locations: ["Lancashire"] },
  { name: "St Albans Gymnastics Club", locations: ["ST ALBANS"] },
  { name: "St Helens Centre For", locations: ["St. Helens"] },
  { name: "St Peter's Gym Club", locations: ["Saltburn-by-the-Sea"] },
  { name: "Stafford Gymnastics Academy", locations: ["Burntwood", "Stafford"] },
  { name: "Stainsby School of Gymnastics", locations: ["Stockton-on-tees"] },
  { name: "Stalder Academy of Gymnastics", locations: ["Sale"] },
  { name: "Stamford Gymnastics Club", locations: ["Stamford"] },
  { name: "Stanmore Gymnastics", locations: ["Stanmore"] },
  { name: "Starbound Gymnastics", locations: ["BROMSGROVE"] },
  { name: "Starjumpers", locations: ["Southampton"] },
  { name: "Starjumpers Gym Club", locations: ["Bristol"] },
  { name: "Stars Academy", locations: ["Welwyn Garden City"] },
  { name: "Stars Gym Club Ltd", locations: ["BRIGHTON", "Brighton", "Hassocks", "Henfield", "Hove", "Lewes", "Pulborough", "WORTHING"] },
  { name: "Stay Active", locations: ["Ongar"] },
  { name: "Stay Active Allstars", locations: ["Saffron Walden", "Sawbridgeworth"] },
  { name: "Stellar Gymnastics", locations: ["Farnham"] },
  { name: "Stenhousemuir Gymnastics Club", locations: ["Falkirk"] },
  { name: "Stevenage Sports Acro", locations: ["Stevenage"] },
  { name: "Stewarton TC", locations: ["Kilmarnock"] },
  { name: "STGWC14", locations: ["South Shields"] },
  { name: "Stirling City GC", locations: ["Stirling"] },
  { name: "Stirling Uni TC & GC", locations: ["Stirling"] },
  { name: "Stockport Rhythmic Gym Club", locations: ["Stockport"] },
  { name: "Stockport School Of Gymnastics Ltd", locations: ["Stockport"] },
  { name: "Stocksbridge Gymnastics", locations: ["Sheffield"] },
  { name: "Stoke Trampolining & Gymnastics Club", locations: ["Stoke-on-Trent"] },
  { name: "Stonehaven", locations: ["Stonehaven"] },
  { name: "Storm Gymnastics", locations: ["Glasgow", "Paisley"] },
  { name: "Streatham Gymnastics Club", locations: ["London"] },
  { name: "Streetly Gymnastics Club", locations: ["Sutton Coldfield"] },
  { name: "Stubbington Springboard Gymnastics", locations: ["Fareham"] },
  { name: "Studley Straddlers", locations: ["Studley"] },
  { name: "Style 90 Gym", locations: ["Stafford"] },
  { name: "Sudbury Gymnastics Club", locations: ["Sudbury"] },
  { name: "Suki Aerobics Gym Club", locations: ["Gosport"] },
  { name: "Summerfields Gym Club", locations: ["Hastings"] },
  { name: "Summersaults", locations: ["Redhill"] },
  { name: "SunnyStarz", locations: ["St Nicholas At Wade"] },
  { name: "Surrey Hills Rhythmic Gymnastics", locations: ["Weybridge"] },
  { name: "Sussex Martlets Trampoline Club", locations: ["Worthing"] },
  { name: "Sussex Springers", locations: ["Hassocks"] },
  { name: "Sutton Gymnastics Academy", locations: ["Sutton"] },
  { name: "Sutton School Of Gymnastics", locations: ["Mitcham"] },
  { name: "Swallows Gym", locations: ["Chelmsford"] },
  { name: "Swallows Of Helston Gym Club", locations: ["Helston"] },
  { name: "Swanage", locations: ["Swanage"] },
  { name: "Swindon School Of Gymnastics", locations: ["Swindon"] },
  { name: "Symmetry Gymnastics Club", locations: ["Chatham"] },
  { name: "Synergy", locations: ["Coventry"] },
  { name: "Synergy Gymnastics London", locations: ["Borough", "Camberwell", "London"] },
  { name: "T J Gymnastics Academy Boston", locations: ["Boston"] },
  { name: "Tamworth Olympic Gym Club", locations: ["Tamworth"] },
  { name: "Tankerton Dancing Academy Gym", locations: ["Whitstable"] },
  { name: "Tanya's Tumblers", locations: ["Sunderland"] },
  { name: "Taunton Trampolining and Gymnastics Academy (TTGA)", locations: ["Taunton"] },
  { name: "Tay Trampoline", locations: ["Dundee"] },
  { name: "Tay Trampoline Club", locations: ["Newport On Tay"] },
  { name: "Team Bath Rhythmic Gymnastics", locations: ["Bath"] },
  { name: "Tees Valley Gymnastics Club", locations: ["Middlesbrough"] },
  { name: "Teesside Academy of Gymnastics", locations: ["Middlesbrough"] },
  { name: "Tekne Gymnastics", locations: ["London"] },
  { name: "Temple-Newsam Halton", locations: ["Leeds"] },
  { name: "Tetbury Gymnastics Club", locations: ["Tetbury"] },
  { name: "TGA Gymnastics Limited", locations: ["Wokingham", "Yateley"] },
  { name: "Thames Valley School of Trampolining", locations: ["Thame"] },
  { name: "Thanet Gymnastic", locations: ["Margate"] },
  { name: "Thanet Gymnastic Club", locations: ["Margate"] },
  { name: "The", locations: ["Bristol", "Gravesend"] },
  { name: "The Academy of Gym", locations: ["Chichester"] },
  { name: "The City Of Leeds YMCA", locations: ["Leeds"] },
  { name: "The Gym Centre", locations: ["Cheltenham", "Gloucester", "Tewkesbury"] },
  { name: "The Gymnastics Academy", locations: ["N Newtownards"] },
  { name: "The Gymnastics and Trampoline Network CIC", locations: ["Ballynahinch", "Belfast", "Downpatrick", "Lisburn"] },
  { name: "The Meapa", locations: ["Rochester"] },
  { name: "The Mill Gymnastics", locations: ["Derby"] },
  { name: "The Norfolk Academy of Gymnastics", locations: ["Attleborough"] },
  { name: "The Trampoline Academy", locations: ["Nuneaton", "Warwick"] },
  { name: "The Triangle Centre", locations: ["Burgess Hill"] },
  { name: "The Vault Portstewart", locations: ["Portstewart"] },
  { name: "The Wire Gymnastic Club", locations: ["Warrington"] },
  { name: "Thornaby & Barwick Gymnastic Club", locations: ["STOCKTON-ON-TEES"] },
  { name: "Thornton Gymnastics", locations: ["Thornton-cleveleys"] },
  { name: "Thurrock Gymnastics Academy", locations: ["Grays"] },
  { name: "Tiger Roll Gymnastics Club", locations: ["Hatfield", "London"] },
  { name: "Tigers Acrobatic Gymnastics", locations: ["Tunbridge Wells"] },
  { name: "Tiggers", locations: ["Dundee"] },
  { name: "Tiggers TC", locations: ["Newport-on-Tay"] },
  { name: "Tir Na Nog", locations: ["Newry"] },
  { name: "Titans Gymnastics Club", locations: ["Wisbech"] },
  { name: "TJ's Gymnastics", locations: ["London"] },
  { name: "TK Gymfit", locations: ["Bradford"] },
  { name: "TK Gymnastics Club", locations: ["Bournemouth"] },
  { name: "Tolworth Gym Club", locations: ["Surbiton"] },
  { name: "Tooting Gymnastics Club", locations: ["London"] },
  { name: "Torbay Olympic Gymnastics", locations: ["Torquay"] },
  { name: "Tornadoes Trampoline Club", locations: ["Market Weighton", "Pocklington"] },
  { name: "Trafford Trampoline Club", locations: ["Manchester"] },
  { name: "Trampoline Life", locations: ["Newcastle Upon Tyne"] },
  { name: "Trix Academy", locations: ["Derby"] },
  { name: "Trumpington Rhythmic Gymnastics", locations: ["Cambridge"] },
  { name: "Truro Gymnastics", locations: ["Truro"] },
  { name: "Tryst GC", locations: ["Falkirk"] },
  { name: "TSD Gymnastics", locations: ["Sheffield"] },
  { name: "TSV", locations: ["Cleckheaton"] },
  { name: "Tumble Gymnastics and Activity Centre", locations: ["Newcastle Upon Tyne"] },
  { name: "Tumble Twist & Turn Gymnastic", locations: ["St. Helens"] },
  { name: "Tumbles Academy of Gymnastics", locations: ["Lowton", "Wigan"] },
  { name: "Turnford Gym Club", locations: ["Cheshunt"] },
  { name: "Twist Gymnastics Club", locations: ["Mansfield"] },
  { name: "Twisters Gymnastics Club Ltd", locations: ["Huntingdon"] },
  { name: "Twisters Northwest Gym", locations: ["Londonderry"] },
  { name: "Twizzlers", locations: ["Croydon", "Purley", "South Croydon"] },
  { name: "Two Foot", locations: ["Musselburgh"] },
  { name: "TyneSide Gymnastics Club", locations: ["Whitley Bay"] },
  { name: "Uckfield Gymnastic", locations: ["Near Uckfield"] },
  { name: "Uist Gymnastics", locations: ["Isle Of Benbecula"] },
  { name: "Ultima Trampoline Club", locations: ["Wickford"] },
  { name: "Ultimate", locations: ["Stourbridge West Midlands"] },
  { name: "Unique Gymnastics", locations: ["LEIGH-ON-SEA"] },
  { name: "Unity Power Tumbling", locations: ["Carshalton"] },
  { name: "University of Bristol Trampoline Club", locations: ["Bath"] },
  { name: "University of Southampton Gymnastics", locations: ["Southampton"] },
  { name: "Up'n'Downs Trampoline Club", locations: ["Seaford"] },
  { name: "Upstarts Gymnastics Club CIO", locations: ["Loughborough"] },
  { name: "Urban School of Gymnastics", locations: ["Warrington"] },
  { name: "Utopia", locations: ["Brighouse", "Wakefield"] },
  { name: "Uttoxeter Gymnastics Club", locations: ["Uttoxeter"] },
  { name: "Valdez Gymnastics CIC", locations: ["Ballymena"] },
  { name: "Velocity", locations: ["Billingham"] },
  { name: "Velocity PSC", locations: ["North Shields", "Whitley Bay"] },
  { name: "Vernon Park Gymnastics", locations: ["Stockport"] },
  { name: "Verve Gymnastics", locations: ["Bedford"] },
  { name: "Victory", locations: ["Petworth"] },
  { name: "Virtue movement", locations: ["Reading"] },
  { name: "Virtuosity Gymnastics Club", locations: ["Rayleigh"] },
  { name: "Virtus", locations: ["Dover"] },
  { name: "Vision", locations: ["Henley-on-thames"] },
  { name: "ViSta Gymnastics", locations: ["Livingston"] },
  { name: "Viva Gymnastics Club", locations: ["Portsmouth"] },
  { name: "Vivace Gymnastics", locations: ["Chislehurst"] },
  { name: "Vivace Gymnastics Club", locations: ["Bromley"] },
  { name: "Wade Gymnastics Club", locations: ["Banbury"] },
  { name: "Wakefield Gym Club", locations: ["Wakefield"] },
  { name: "Walsall Gym Club", locations: ["Walsall"] },
  { name: "Walton Gym", locations: ["Walton-on-thames"] },
  { name: "Wansbeck Gymnastics and Trampoline Club", locations: ["ASHINGTON"] },
  { name: "Wantage Gymnastics", locations: ["Stanford In The Vale"] },
  { name: "Ware Gym Club", locations: ["Ware"] },
  { name: "Warrington Gymnastics", locations: ["Warrington"] },
  { name: "Washindi Trampoline Club", locations: ["Crowthorne"] },
  { name: "Washington Gymnastics Club", locations: ["Washington"] },
  { name: "Waterside Gymnastic", locations: ["Southampton"] },
  { name: "Watford Gymnastics Club", locations: ["Watford"] },
  { name: "Waveney Gymnastics", locations: ["Lowestoft"] },
  { name: "Weald Gymnastics Club", locations: ["Tonbridge"] },
  { name: "West Bromwich Gym & Trampoline", locations: ["Wednesbury"] },
  { name: "West Cumbria Gym Club", locations: ["CLEATOR"] },
  { name: "West Dunbartonshire GC", locations: ["Dumbarton"] },
  { name: "West Hull Gymnastics Club", locations: ["Hull"] },
  { name: "West London Gymnastics", locations: ["Greenford"] },
  { name: "West Lothian Artistic GC", locations: ["Bonnyrigg", "Livingston"] },
  { name: "West Wight Trampoline Club", locations: ["Freshwater Isle of Wight"] },
  { name: "West Wiltshire Esprit Gymnastics Club Ltd", locations: ["Trowbridge"] },
  { name: "Westcliff Trampoline Club", locations: ["Hawkwell"] },
  { name: "Westgate", locations: ["Chichester"] },
  { name: "Weston Gymnastics Centre", locations: ["Weston Super Mare"] },
  { name: "Wetherby Gymnastics Club", locations: ["Boston Spa", "Wetherby"] },
  { name: "Weybourne Gym Club", locations: ["Addlestone"] },
  { name: "Weybridge Gym", locations: ["Weybridge"] },
  { name: "Weymouth & Portland Gym Club", locations: ["Weymouth"] },
  { name: "Whirlwinds", locations: ["Wellington", "Weston-super-mare"] },
  { name: "White Oak Gym Club", locations: ["Swanley"] },
  { name: "White Rose Rythmic Gymnastics club", locations: ["Huddersfield"] },
  { name: "Whitehall Gymnastics Club", locations: ["Colchester"] },
  { name: "Whitehaven Gymnastics Club", locations: ["Whitehaven Cumbria"] },
  { name: "WhiteRose Gymnastics Limited", locations: ["Goole"] },
  { name: "Wickers Gym", locations: ["Lancing"] },
  { name: "Wickford Trampoline Centre", locations: ["Wickford"] },
  { name: "Wigan ABC Gymnastics", locations: ["Wigan"] },
  { name: "Wigan Academy of Gymnastics", locations: ["Wigan"] },
  { name: "Wight Flyers Trampoline Club", locations: ["Newport"] },
  { name: "Wigton Gymnastics", locations: ["Wigton"] },
  { name: "WildKatz", locations: ["Hucknall"] },
  { name: "Wilmslow Academy of", locations: ["Wilmslow"] },
  { name: "Wiltshire School Of Gymnastics", locations: ["Melksham"] },
  { name: "Wimbledon Gymnastics Centre", locations: ["London"] },
  { name: "Wirral Gymnastics", locations: ["Prenton"] },
  { name: "Wirral Trampoline Club", locations: ["Birkenhead"] },
  { name: "Witham Hill Gymnastics", locations: ["Lincoln"] },
  { name: "Woburn Sands Gymnastics", locations: ["Milton Keynes"] },
  { name: "Woking Gymnastics", locations: ["Woking"] },
  { name: "Wolds Gymnastics", locations: ["Driffield"] },
  { name: "Woodland Acrobatic Gym Club", locations: ["Flitwick"] },
  { name: "Woodlands Acro-Gymnastics and Trampolining Club", locations: ["Coventry"] },
  { name: "Worcestershire Gymnastics Academy", locations: ["Worcester"] },
  { name: "Worcestershire Special Olympic", locations: ["Kidderminster"] },
  { name: "Worksop Gymnastics Club", locations: ["Worksop"] },
  { name: "Worthing Gymnastics Club", locations: ["Worthing"] },
  { name: "Wotton-under-Edge Gym Club", locations: ["Wotton-under-Edge"] },
  { name: "Wycombe Gymnastics", locations: ["High Wycombe"] },
  { name: "Wyre Forest Gymnastic", locations: ["Kidderminster"] },
  { name: "Wythall Gymnastics Club", locations: ["Birmingham"] },
  { name: "Xcel Gymnastics", locations: ["Waterlooville"] },
  { name: "YMCA North London Gymnastics Club", locations: ["London"] },
  { name: "York City Gymnastics", locations: ["York"] },
  { name: "Zenith Trampoline Club", locations: ["Potters Bar"] },
  { name: "Zero Gravity Academy of Gymnastics and Trampoline", locations: ["Saltash"] },
  { name: "Zippy's Gymnastics Academy", locations: ["Glasgow"] },
  { name: "Zodiac Gymnastics Club", locations: ["Caterham"] }
];
